### ISSUE TITLE
sample repo https://github.com/infra-team/cluster-deployments.git missing 

### ISSUE THREAD

**Issue by librannk** [argoproj-labs/applicationset#101]
sample repo for applicationset link is broken.

https://github.com/infra-team/cluster-deployments.git

getting 404 on the sample repo, can anyone fix the same or provide the updated link ?

**Comment by mgoodness** [comment]
@librannk those files are only examples; they are not intended to point to actual config.

**Comment by jgwest** [comment]
As @mgoodness said, those files are only simple examples, and they don't have a corresponding git repository backing them.

That said, I agree that it is confusing (when I was new to the project I was a bit surprised they didn't exist as well). This should be improved by these issues:
- Reorganize the examples directory: https://github.com/argoproj-labs/applicationset/issues/77
- Better documentation: https://github.com/argoproj-labs/applicationset/issues/84
- Proper examples: https://github.com/argoproj-labs/applicationset/issues/85
