### ISSUE TITLE
Create helm chart

### ISSUE THREAD

**Issue by maruina** [argoproj-labs/applicationset#120]
Hi all,
I see that Argo provides Helm charts to install ArgoCD or other tools (see https://github.com/argoproj/argo-helm/tree/master/charts). Are you planning to add an helm chart for the ApplicationSet as well? 

I'm happy to raise a PR. Should it be in the same ArgoCD chart as an option or a separate chart?

**Comment by OmerKahani** [comment]
I think it can be part of the ArgoCD chart

**Comment by maruina** [comment]
Ok, I will have a look and raise a PR there. Do you have a published docker image for the AppSet controller like https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml#L11?

**Comment by jgwest** [comment]
I'd suggest a standalone ApplicationSet chart to begin with, as this would allow folks to install ApplicationSet alongside their existing Argo CD install.

We haven't put out an official 0.1.0 image out (still working our way through the [Milestone 1](https://github.com/argoproj-labs/applicationset/milestone/1) issues), but I've put out an image you can use for your testing:

I created a prerelease image `quay.io/argocdapplicationset/argocd-applicationset:v0.1.0-prerelease` here: 
https://quay.io/repository/argocdapplicationset/argocd-applicationset?tab=tags

The corresponding install artifacts are on my personal branch (https://github.com/jgwest/applicationset/tree/release-0.1.0):
```
Install ApplicationSet Controller:
kubectl apply -n argocd -f https://raw.githubusercontent.com/jgwest/applicationset/v0.1.0/manifests/install.yaml

Install ApplicationSet Controller + Argo CD v1.8.4:
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/jgwest/applicationset/v0.1.0/manifests/install-with-argo-cd.yaml
```

As above, this is a temporary pre-release image, for testing purposes only. When we put out our first official release, this tag will be removed.

**Comment by maruina** [comment]
Ok thanks, I'll raise a PR to add a separate applicationset helm chart and
then we can iterate from there. I will use the kustomize directory as a
base to create the chart. I should be able to start working on that in the
next few days.

**Comment by maruina** [comment]
Started a draft PR: https://github.com/argoproj/argo-helm/pull/577

**Comment by maruina** [comment]
@jgwest I'm tagging you here as well for visibility. I have the chart working but the tests are failing because of
```
[ERROR] templates/crds.yaml: the kind "apiextensions.k8s.io/v1beta1 CustomResourceDefinition" is deprecated in favor of "apiextensions.k8s.io/v1 CustomResourceDefinition"
```

**Comment by jgwest** [comment]
@maruina I was able to get past that by using the following to generate the CRD in the ApplicationSet Makefile:
```
# Generate manifests e.g. CRD, RBAC etc.
.PHONY: manifests
manifests: generate
        $(CONTROLLER_GEN) crd:crdVersions=v1 paths="./..." output:crd:artifacts:config=./manifests/crds/ # <-- crdVersions
        hack/generate-manifests.sh
```
But these update CRDs causes the E2E tests to fail :disappointed:  . @mgoodness reported [the same issue on Argo community slack](https://argoproj.slack.com/archives/C014ZPM32LU/p1610566935065100). I spent some time looking at it again and unfortunately the E2E tests don't appear to be doing anything that is obviously incorrect, but I still have some leads to follow...

**Comment by maruina** [comment]
Ok thanks. I can update the helm chart with the v1 CRDs to make the test passing, but I guess we want to bump the version here as well.

Should we hold merging the AppSet chart until then?

**Comment by maruina** [comment]
FYI, I used the draft Helm chart internally and it works. It's just Helm complaining about the CRD version.

**Comment by jgwest** [comment]
@maruina This should fix the issue in ApplicationSet: https://github.com/argoproj-labs/applicationset/pull/128

Once merged, I'll regenerate the manifests linked on [my previous comment](https://github.com/argoproj-labs/applicationset/issues/120#issuecomment-777027682).

**Comment by jgwest** [comment]
@maruina I've merged #128 , closing #127, which should fix the issue you are seeing. You can grab the latest versions from the same URLs used in my [previous comment](https://github.com/argoproj-labs/applicationset/issues/120#issuecomment-777027682).

**Comment by maruina** [comment]
Thank you, I will have a look in the next couple of days!

**Comment by maruina** [comment]
All tests are passing, just waiting a review 🎉

**Comment by jgwest** [comment]
https://github.com/argoproj/argo-helm/tree/master/charts/argocd-applicationset :tada:
