### ISSUE TITLE
Git Directory Generator only matches directories that contain valid Helm/ksonnet/Kustomize artifacts

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#121]
The Git Directory generator is currently calling Argo CD repo-server's `ListApps` function, in order to discover the list of directories that are available in the repository.

However, that function only returns directories that contain Argo CD applications (and it excludes directory-only applications), specifically those that [match the set of rules here](https://github.com/argoproj/argo-cd/blob/1d1fbf0fb17d5c47ff269b3232d090dc507e0b8d/util/app/discovery/discovery.go#L14), and [described in the docs here](https://argoproj.github.io/argo-cd/user-guide/tool_detection/).

While this works well for Argo CD, it doesn't fully fit our needs... as per the design doc, Git Directory should consider all directories, not just those that contain kssonet, Helm, or Kustomize artifacts.

So a couple better solutions are:
1) Either: Use `repo_service.go`'s `GetPaths` instead of `GetApps`, in order to gather the list of directories
2) Or: add a new function to Argo CD repo service to return a full list of paths.

IMHO I prefer option 1 (reserving the right to implement option 2 in the future, if we find that too much CPU/network resources are consumed by option 1).

**Comment by OmerKahani** [comment]
As we now have `GetPaths` we should go with that. Option 2 is a useful contribution for ArgoCD that also has this problem in the add application UI (which uses the same `GetApps` function)
