### ISSUE TITLE
HA Support?

### ISSUE THREAD

**Issue by jbaskeen** [argoproj-labs/applicationset#129]
Does the current implementation support HA? I am currently using AppSet in a production environment and would like to know if there is a known limitation with running multiple replicas (3).

**Comment by maruina** [comment]
Hey, I think that with https://github.com/argoproj-labs/applicationset/pull/125 is merged you can run it in leader election mode.

**Comment by jbaskeen** [comment]
Thanks @maruina, I will try this out today and close this is all is good

**Comment by jbaskeen** [comment]
This appears to be working as expected. Thanks @maruina

**Comment by mabusaa** [comment]
@jbaskeen can you please share how you enable the HA mode ?
