### ISSUE TITLE
non-existent docker image referenced in manifest

### ISSUE THREAD

**Issue by sachincool** [argoproj-labs/applicationset#149]
Hi! 
I tried to install the applicationset CRD into my cluster and found that the docker images for controller deployment doesn't exist.
[manifests](https://github.com/argoproj-labs/applicationset/blob/master/manifests/install.yaml#L1539)
```
docker pull argoprojlabs/
argocd-applicationset:latest
Error response from daemon: pull access denied for argoprojlabs/argocd-applicationset, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
can you point me to the correct image if exists? makefile also points to this image.

**Comment by jgwest** [comment]
Hi @sachincool , we haven't put out an official first release yet (very soon!), hence the invalid image references. In the mean time, you can access the *pre-release* images here:

**Install instructions**: https://argocd-applicationset.readthedocs.io/en/stable/Geting-Started/#installation

**Images**: https://quay.io/repository/argocdapplicationset/argocd-applicationset?tab=tags (edited)

**Comment by sachincool** [comment]
Thanks @jgwest closing the issue.

**Comment by rumstead** [comment]
@jgwest, why not publish a "latest" image on every commit to master?

**Comment by jgwest** [comment]
@rumstead Working on it :smile:.
