### ISSUE TITLE
No Kind ApplicationSet registered for argoproj.io/v1alpha1

### ISSUE THREAD

**Issue by soumentrivedi** [argoproj-labs/applicationset#15]
Hello,
I am trying to evaluate ApplicationSet in my k8s cluster and get the following error when we deploy the applicationset

`error: no kind "ApplicationSet" is registered for version "argoproj.io/v1alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"`

applicationset.yaml that I am using is
`apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: helm-guestbook
      namespace: kube-system
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: HEAD
        path: helm-guestbook
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system`

I am simply trying to see if we get an app generated even though i am not using the parameters currently.

**Comment by dgoodwin** [comment]
Did you run kubectl apply -f manifests/crds/ to create the custom resource definitions?

**Comment by soumentrivedi** [comment]
yes the CRD is present already

**Comment by dgoodwin** [comment]
Can you retest this with latest master, and the documented deploy steps in the README.

**Comment by soumentrivedi** [comment]
this is fixed in master branch so nothing else to do. i am able to use this now thanks!
