### ISSUE TITLE
Sanitize cluster name field by replacing unsupported characters

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#166]
The cluster name (coming from the cluster as defined within Argo CD), may contain invalid characters for some Application fields (ie `.metadata.name`). This poses a problem when the Cluster generator produces the cluster name as a param, and that param is used in a field which doesn't allow those characters. We should sanitize the cluster name by replace unsupported characters for fields that don't support those characters (see the rules for `.metadata.name`, below)

Example:

OpenShift clusters imported into Argo CD use a cluster name based on the Kube config context. The name format for the context  uses forward slashes `default/api-cluster1-cluster-host-com:6443/kube:admin`

Which when using Cluster generator, and using that cluster name in the `metadata.name` field, produces this error:
`
time="2021-03-20T22:04:52Z" level=error msg="failed to unchanged Application" action=unchanged app="(...)" appSet=bgd error="Application.argoproj.io \"default/api-cluster1-cluster-host-com:6443/kube:admin\" is invalid: metadata.name: Invalid value: \"default/api-cluster1-cluster-host-com:6443/kube:admin\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
`

**Comment by chetan-rns** [comment]
@jgwest Could you please assign it to me? Will give it a try over the weekend :)
