### ISSUE TITLE
Rebase to go.mod to latest Argo CD v2.0, adopt new APIs as needed, and retest

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#174]
Once ApplicationSet v0.1.0 and Argo CD v2.0 are out the door, we should adopt the latest Argo CD v2.0 (attempting to keep backwards compatibility where it is straightforward), including fixing any changed APIs, and retesting.

**Comment by joebowbeer** [comment]
The combined v0.1.0 ApplicationSet + ArgoCD installation is installing argocd 2.0.0, while its current stable version is 2.0.3. Can you release a combined manifest that tracks the latest stable argocd?
