### ISSUE TITLE
Document support for matchExpression

### ISSUE THREAD

**Issue by RichiCoder1** [argoproj-labs/applicationset#185]
In order to select multiple specific clusters with different label values, it'd be nice to specify a match expression ala https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements.

**Comment by mgoodness** [comment]
`matchExpressions` is supported in the cluster generator, though the example doesn't demonstrate it.

**Comment by RichiCoder1** [comment]
Ah! Excellent, I guess this is more of a docs issue then
