### ISSUE TITLE
Is it possible to extract more information than server and name from cluster generator ?

### ISSUE THREAD

**Issue by aelbarkani** [argoproj-labs/applicationset#194]
Hi!

I use cluster generator with label selector, and would like to extract more fields than just server and name from the ArgoCD secrets that contain cluster information. Is that supported ?
I tried adding a custom key in the secret (clusterdomain for example) and using it at the ApplicationSet, but it seems it doesn't work.

**Comment by jgwest** [comment]
Hi @aelbarkani , you should be able to use the `metadata.labels.*` values and `metadata.annotations.*` for this. See [here](https://argocd-applicationset.readthedocs.io/en/stable/Generators/#cluster-generator) for details.
