### ISSUE TITLE
ApplicationSets that initially fail validation might not be re-reconciled

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#219]
ApplicationSets that are invalid the first time that they are processed might become valid at a later time. For example:
- A `project` is referenced that doesn't exist at time of ApplicationSet create, but is later created
- A `cluster` is referenced that doesn't exist at time of creation, but is later created.

But the way that we are currently processing errors from `validateGeneratedApplications` means that we just assume that all errors are 'permanent', eg they will continue to fail indefinitely without some user action (updating the CR).

In retrospect this is an incorrect assumption, and we should instead set a `RequeueAfter` time (60 seconds?) rather than just returning a nil result.

**Comment by travisghansen** [comment]
Thanks for addressing!
