### ISSUE TITLE
Support Webhooks trigger For Git generators in application set

### ISSUE THREAD

**Issue by mksha** [argoproj-labs/applicationset#222]
Currently in application set if we use git generator files, then it will poll the specified repo in every 3 min, but I think either we should allow the use to change the polling period or support the use of git webhook For Git generators so the changes to the files can be detected immediately rather than waiting for 3 min.

**Comment by chetan-rns** [comment]
@jgwest I would like to work on this. Could you please assign it to me?

**Comment by c0deaddict** [comment]
Would love to see this in applicationset :heart: Any update on this?

**Comment by chetan-rns** [comment]
@c0deaddict  I've started looking into it. Will try to get the PR ready this week

**Comment by c0deaddict** [comment]
Awesome! :heart:
