### ISSUE TITLE
TestGetFileContent test is failing when running go test, on Mac

### ISSUE THREAD

**Issue by mksha** [argoproj-labs/applicationset#245]
```
time="2021-05-26T16:26:29+05:30" level=info msg=Trace args="[git clean -fdx]" dir="/var/folders/55/y1ln_mzn4cg9f605bphmkgbc0000gr/T/https:__github.com_argoproj_argocd-example-apps_" operation_name="exec git" time_ms=14.280113
--- FAIL: TestGetFileContent (5.86s)
    --- FAIL: TestGetFileContent/pull_an_invalid_file (1.23s)
        repo_service_test.go:348: 
                Error Trace:    repo_service_test.go:348
                Error:          Error message not equal:
                                expected: "open /tmp/https:__github.com_argoproj_argocd-example-apps_/this-file-does-not-exist.md: no such file or directory"
                                actual  : "open /var/folders/55/y1ln_mzn4cg9f605bphmkgbc0000gr/T/https:__github.com_argoproj_argocd-example-apps_/this-file-does-not-exist.md: no such file or directory"
                Test:           TestGetFileContent/pull_an_invalid_file
FAIL
coverage: 79.4% of statements
FAIL    github.com/argoproj-labs/applicationset/pkg/services    17.205s
ok      github.com/argoproj-labs/applicationset/pkg/services/scm_provider       7.943s  coverage: 65.2% of statements
ok      github.com/argoproj-labs/applicationset/pkg/utils       3.015s  coverage: 71.2% of statements
FAIL
make: *** [test] Error 1
```

**Comment by mksha** [comment]
@jgwest when we tried to build an image using master branch that seems like go tests are failing.

**Comment by jgwest** [comment]
Hi @mksha , interesting, can you provide more information on how are you building your image:
- Version of Docker/Podman (including operating system version)
- Exact command used to build it
- Exact Dockerfile used to build it

And if you have any idea why your OS temporary directory is `/var/folders/55/y1ln_mzn4cg9f605bphmkgbc0000gr/T/` rather than `/tmp` that would be useful too. I'm guessing this is a mac thing :stuck_out_tongue:

**Comment by jgwest** [comment]
Ah, figured it out, looks like Mac doesn't use `/tmp` as temp directory, and we've hardcoded `/tmp` in the test itself. I will fix it, and In the mean time, as a workaround, you can comment out that test.

**Comment by mksha** [comment]
yeah, that is the issue, sorry for late response.

**Comment by mksha** [comment]
for now, i pointed the location to my system's temporary location :)
