### ISSUE TITLE
.metadata.finalizers cannot be turned off for the generated apps

### ISSUE THREAD

**Issue by marcozov** [argoproj-labs/applicationset#254]
Any application created by an ApplicationSet also comes with a configured `.metadata.finalizers` field: https://argocd-applicationset.readthedocs.io/en/stable/Application-Deletion/ .

While this is a nice feature and it makes sense for 90% of the cases, there could still be the chance where it can be desirable to be able to turn it off.
For instance, if we are using the git generator and we want to rename an argocd application (by simply renaming the folder that contains the k8s resources), this configuration will delete the application + the all the k8s resources inside, and then create a new application with the same resources.

In this case, wouldn't it make sense to **not** delete the k8s resources created by the argocd Application ( = remove the finalizer), change the application name ( = delete the app and create it again), and update (either with argocd sync or with a manual patch) the resources to have the correct label (`argocd.argoproj.io/instance` to indicate the parent app name) ?

**Comment by jgwest** [comment]
Hi @marcozov, this should now be handled by https://github.com/argoproj-labs/applicationset/pull/223 with the `preserveResourcesOnDeletion` field, see [here](https://github.com/argoproj-labs/applicationset/blob/master/docs/Application-Deletion.md) for a description of the new behaviour.

**Comment by meier-christoph** [comment]
Hi @jgwest, do you have an idea of when this will be available in a release ?

Yesterday, I deleted the wrong ApplicationSet by mistake and it started to teardown 2 of our clusters. I got lucky and it was not our production but still this is way too dangerous for our use case and I would like to know whether I should fork this project or if this will be available soon.

**Comment by jgwest** [comment]
Hi @meier-christoph , the plan is to release end of July (alongside Argo CD v2.1).

**Comment by agaudreault-jive** [comment]
Is there a way to set `preserveResourcesOnDeletion: true` as the default behavior in the applicationSet controller ? If not, do you think that would be a good feature ?
