### ISSUE TITLE
Remove the unused SkipPrune option from ApplicationSetSyncPolicy

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#261]
The `SkipPrune` option in `ApplicationSetSyncPolicy` has never been implemented, and is currently unusued, AFAICT, and is likewise not referenced in any examples or in the initial design doc. 

The behaviour described by the comment on `SkipPrune` is handled by a non-cascading delete, and by `preserveResourcesOnDeletion`. See the [Application Deletion behaviour](https://github.com/argoproj-labs/applicationset/blob/master/docs/Application-Deletion.md) page for details.

`SkipPrune` should thus be removed from `ApplicationSetSyncPolicy`.

**Comment by ishitasequeira** [comment]
@jgwest I would like to work on this issue.
