### ISSUE TITLE
ClusterDecisionResource support for labels.

### ISSUE THREAD

**Issue by jnpacker** [argoproj-labs/applicationset#271]
## Current functionality
In the ClusterDecisionResource generator, we find the decision resource using the resources name.  

## Problem
There will be cases where the name for this resource may come from `metadata.generateName`, where we don't want to always be updating the ApplicationSet spec (such as a gitops flow).  There are also cases where one might desire to select multiple decision resources to combine the results.

## Proposed solution
Add metav1.labelSelector, as a field in the clusterDecisionResource generator, so one can use `name` or `labelSelector.matchLabels` or `labelSelector.matchExpressions`

**Comment by jgwest** [comment]
I believe this is now completed, since #272 has merged.
