### ISSUE TITLE
Add support for gitlab in SCM generator

### ISSUE THREAD

**Issue by yogeek** [argoproj-labs/applicationset#280]
Hello :-)

SCM generator is awesome, but I cannot use it for now because we use a private gitlab instance.
As the question about it has not been answered in Slack, I open this issue to know if some work has been started on gitlab support into the SCM generator.
Thanks

**Comment by jgwest** [comment]
Hi @yogeek, adding GitLab support would be great! The SCM provider generator (and it's GitHub support) was contributed by an Argo CD community member, and likewise GitLab support would need to come from community folks that are interested in this feature. 

TLDR: PR requests welcome :smile: .

**Comment by yogeek** [comment]
Hi @jgwest , ok thanks for your answer 👍
I do not know golang but I will try to have a look into the gitlab go library to explore and identify where to start.

**Comment by zwennesm** [comment]
Not trying to hijack this issue but it might be related. I am getting the following error when applying an `ApplicationSet` with a private Gitlab repository using HTTPS using the git generator. Is this the same issue or just a misconfiguration?

```
│ time="2021-07-05T15:47:49Z" level=info msg="git fetch origin --tags --force" dir="/tmp/https:__gitlab.com_XXXX" execID=MhWrr                                                                                              │
│ time="2021-07-05T15:47:49Z" level=error msg="`git fetch origin --tags --force` failed exit status 128: fatal: could not read Username for 'https://gitlab.com': No such device or address" execID=MhWrr                                  │
│ time="2021-07-05T15:47:49Z" level=info msg=Trace args="[git fetch origin --tags --force]" dir="/tmp/https:__gitlab.com_mobilab-020_mobilab" operation_name="exec git" time_ms=274.169878                                                 │
│ time="2021-07-05T15:47:49Z" level=error msg="error generating params" error="Error during fetching repo: `git fetch origin --tags --force` failed exit status 128: fatal: could not read Username for 'https://gitlab.com': No such devi │
│ time="2021-07-05T15:47:49Z" level=error msg="error generating application from params" error="Error during fetching repo: `git fetch origin --tags --force` failed exit status 128: fatal: could not read Username for 'https://gitlab.c │
│ 2021-07-05T15:47:49.678Z    ERROR    controller-runtime.manager.controller.applicationset    Reconciler error    {"reconciler group": "argoproj.io", "reconciler kind": "ApplicationSet", "name": "core", "namespace": "argocd", "error" │
│ github.com/go-logr/zapr.(*zapLogger).Error
```
