### ISSUE TITLE
How to remove a single application from ApplicationSets

### ISSUE THREAD

**Issue by sreejithwpg** [argoproj-labs/applicationset#312]
is it possible to remove a single application from ApplicationSets temporarily and add it later

**Comment by jgwest** [comment]
Hi @sreejithwpg, not at this time - I wrote up a new doc page on this topic you might be interested in: https://github.com/argoproj-labs/applicationset/blob/master/docs/Controlling-Resource-Modification.md

**Comment by sreejithwpg** [comment]
Hi @jgwest 
Thanks for your clarification. One more question is it possible to manage applicationSets using API?
Also, in a scenario like I have created an application and deploying an application using git generator. I just removed one directory from the git repo and resynced the applicationSet. Will the applicationSet remove the application that corresponds to the removed directory?

**Comment by jgwest** [comment]
RE: API, not at this time, but I can certainly see the benefit of that. Right now all interactions with ApplicationSet controller are via the `ApplicationSet` resource in k8s.

Re: Removing a directory from git repo, yes the Application will be removed as soon as next the git generator sync happens.

**Comment by sreejithwpg** [comment]
Hi @jgwest 

Is there any way to sync the controller forcefully? Like using API or argocd cli

Thanks in advance

**Comment by jgwest** [comment]
@sreejithwpg not yet, that feature is being track here: https://github.com/argoproj-labs/applicationset/issues/222

**Comment by sreejithwpg** [comment]
@jgwest Thanks for the update
