### ISSUE TITLE
Add SyncPolicy Prune

### ISSUE THREAD

**Issue by OmerKahani** [argoproj-labs/applicationset#33]
From the Proposal https://docs.google.com/document/d/1juWGr20FQaJmuuTIS8mBFmWWDU422M_FQMuhp5c1jt4/edit#

**Comment by dgoodwin** [comment]
SyncPolicy.Prune makes sense to me.

Does SyncPolicy.InitialSync have any relation to ApplicationSets? In ArgoCD you get those Applications in the UI that you can manually sync, but that's not really a thing here with ApplicationSet. We'd just log what we generated and you'd get no result, which doesn't seem overly useful. 

Feels like we just want prune here?

**Comment by dgoodwin** [comment]
I will start working on this today.
