### ISSUE TITLE
Bug: Add support for argocd v2.1

### ISSUE THREAD

**Issue by m-yosefpor** [argoproj-labs/applicationset#340]
In argocd v2.1, the repositories and repository credential templates have been factored out of argocd-cm to separate secrets. [docs link](https://argoproj.github.io/argo-cd/operator-manual/upgrading/2.0-2.1/#replacing-repositories-and-repositorycredentials-with-secrets) . Argocd application controller does not currently support this format and will result in `Permission denied` Errors on those private repositories. Adding those repos manually back to argocd cm will fix the issue, however, creating repos from UI will create only the separate secrets by default, so the ApplicationSet controller won't work with that.

Tested with argocd v2.1-rc3.

P.S. IMHO merging this repository with argocd repo will avoid future similar issues, and drops the need for a version compatibility matrix or blocking upgrades. There are other benefits as explained in this issue https://github.com/argoproj-labs/applicationset/issues/244

**Comment by jgwest** [comment]
Hi @m-yosefpor , these should now be supported as of https://github.com/argoproj-labs/applicationset/pull/310, what version of ApplicationSet controller are you testing with?
