### ISSUE TITLE
Git file generator should support {{path.basename.parentfolder}}

### ISSUE THREAD

**Issue by Checksumz** [argoproj-labs/applicationset#350]
It would be useful to be able to use {{path.basename.parentfolder}} template variable in git-files generator, to get parent folder name of chart deployed. Assuming one has the below folder structure one can easily obtain the parent folder while running the application set which can be used for the namespace variable in the destination.

```
apps
└─ namespace-name
        └─ app 1
        └─ app 2
        └─ app 3       
```      
                  
eg 1:
path: kube-infra/dns-infra/*
path.basename.parentfolder: dns-infra
eg 2:
path: kube-infra/database/*
path.basename.parentfolder: database

applicationset.yaml below

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-infra-setup
  namespace: ci-cd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: git@github.com:xxxx/k8s.git
          revision: HEAD
          directories:
          - path: kube-infra/dns-infra/*
          - path: kube-infra/database/*
        exclude: 
      - list:
          elements:
          - cluster: dev
            url: https://xxx.xxx.xxx.xxx           
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: xxxx
      source:
        repoURL: git@github.com:xxxx/k8s.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
            - '{{cluster}}-{{path.basename}}-values.yaml'
      destination: 
        server: '{{url}}'
        namespace: '{{path.basename.parentfolder}}'
      syncPolicy:
        automated: 
            prune: true 
            selfHeal: true 
        syncOptions:     
        - CreateNamespace=true

**Comment by Checksumz** [comment]
@jgwest  i was planning to write code for this if this gets approved, please let me know your thoughts on it.

**Comment by jgwest** [comment]
Hey @Checksumz , check out this issue, and let me know what you think: https://github.com/argoproj-labs/applicationset/issues/293

**Comment by Checksumz** [comment]
Thanks @jgwest that looks good, sorry for the delayed reply
