### ISSUE TITLE
applicationset could not generate applications while when encountered an error in validateGeneratedApplications.

### ISSUE THREAD

**Issue by tuxknight** [argoproj-labs/applicationset#352]
The controller could not generate applications after fix errors in validateGeneratedApplications.

Version:   `quay.io/argocdapplicationset/argocd-applicationset@sha256:bd62ff6ee18f16e9021ae89e347cd6ded960d6054bdd3c608fc05acdf8a03bc3`

Detail logs:

```
time="2021-08-24T02:34:56Z" level=info msg="git ls-files --full-name -z -- */qa/*/config.json" dir="/tmp/https:__xxxxxx" execID=OacSt
time="2021-08-24T02:34:56Z" level=info msg=Trace args="[git ls-files --full-name -z -- */qa/*/config.json]" dir="/tmp/https:__xxxxxx" operation_name="exec git" time_ms=9.673257
time="2021-08-24T02:34:57Z" level=error msg="application references project qa which does not exist"
```

This error was due to the missing application project qa. But after creating project qa, applications are not generated.

**Comment by jgwest** [comment]
Hi @tuxknight , this is likely due to https://github.com/argoproj-labs/applicationset/issues/126 , which has been fixed in v0.2.0.
