### ISSUE TITLE
Pass a list on git files generator

### ISSUE THREAD

**Issue by AndresJulia** [argoproj-labs/applicationset#353]
Argo doesn't seem to recognize ```{{app.test}}```  list on the config.json

```
{
  "app": {
    "test": ["a", "b", "c", "d"],
  }
}

```

Is there any way around this ?

**Comment by jgwest** [comment]
Hi @AndresJulia, not at this time, this is being tracked here:

https://github.com/argoproj-labs/applicationset/issues/362
