### ISSUE TITLE
policy=create-update - applications still deleted

### ISSUE THREAD

**Issue by jamessthompson** [argoproj-labs/applicationset#359]
I've configured the applicationset controller with a policy of create-update per https://argocd-applicationset.readthedocs.io/en/stable/Controlling-Resource-Modification/#policy-create-update-prevent-applicationset-controller-from-deleting-applications

I can see the policy being passed into the controller 

```
➜ kgp  argocd-argocd-applicationset-799df9fbf6-v9sf5 -o 'custom-columns=:.spec.containers[0].command'

[applicationset-controller --metrics-addr=:8080 --probe-addr=:8081 --namespace=argocd --argocd-repo-server=argocd-repo-server:8081 --policy=create-update --debug=false --dry-run=false]
```
When I apply the appliationset into the argocd namespace, I see applications created for each chart in my git repo.

When I delete the applicationset from the argocd namespace, all the applications are deleted.

My expectation was that the applications would remain.

If it makes any difference, I have two instances of ArgoCD installed in two namespaces (argocd, argocd-infra) with an applicationset controller installed in each namespace.

**Comment by jgwest** [comment]
Hi @jamessthompson , the linked page refers only to whether the ApplicationSet controller itself is 'allowed' to delete applications. It does not prevent the user from deleting ApplicationSets themselves (eg via `kubectl`) 

See https://argocd-applicationset.readthedocs.io/en/stable/Application-Deletion/ for behaviour on how this workflow works.
