### ISSUE TITLE
ApplicationSet (Git Generator) deletes itself when started by another Application or ApplicationSet

### ISSUE THREAD

**Issue by namh0** [argoproj-labs/applicationset#400]
## Summary

When using an "app of apps" pattern with `ApplicationSets` and the Git directory generator, the second `ApplicationSet` deletes itself and often causes other applications to be deleted with it. 

EDIT: This seems to happen even if the first app is an `Application` rather than `ApplicationSet`.

## Details

ArgoCD version 2.2.0
ApplicationSet version 0.2.0

Tested on Minikube with Kubernetes version 1.22 and EKS with Kubernetes version 1.20

## Replication Steps

1. Define an `ApplicationSet` with the Git directory generator. 
2. In the target directory, add another `ApplicationSet` with the Git directory generator, pointing at another directory. 
3. The above two steps should be enough to see that the second `ApplicationSet` and the generated `Application` resource is marked for deletion. 
4. Add `Applications` or other resources in the target directory of the second `ApplicationSet`. These resources will either never create or immediately mark itself for deletion. 

## Additional Details

On occasions, the resources of the second `ApplicationSet` will create and persist, but the `ApplicationSet` itself will remain in delete state.

If there were other resources besides the `ApplicationSet` in the directories from the first `ApplicationSet`, those services will also get deleted along with the second `ApplicationSet`. 

For example: 

```
├── appset.logs
├── manifests
├── nginx
│   └── app.yml
├── root_appset.yaml
└── services
    ├── argotest
    │   └── appset.yaml
    ├── crossplane
    │   └── application.yaml
    └── nginx
        └── nginx-app.yaml
```

The `root_appset` uses Git generator to look in `services`. The resources `crossplane` and `nginx` will also delete themselves due to issues with the `argotest/appset.yaml`.

Applying the second `ApplicationSet` directly, without the first, results in the resources being deployed correctly.  

Using list generator results in the resources being deployed correctly. 

## Logs

[appset_logs.tar.gz](https://github.com/argoproj-labs/applicationset/files/7437303/appset_logs.tar.gz)

**Comment by jgwest** [comment]
@namh0 Can you provide the `ApplicationSet` CRs you used to reproduce the problem?

**Comment by namh0** [comment]
@jgwest - I have a repo with the manifests: https://gitlab.com/namho/argotest/

Applying the `root_appset.yaml` should be enough to replicate the behavior.

**Comment by jgwest** [comment]
It looks like your `root_appset.yaml` is conflicting with your `services/argotest`: the ApplicationSets both have the same name.

**Comment by namh0** [comment]
(>ლ) - Sorry for wasting your time. I could've sworn there was another trigger to cause it but looking at my Git history on the actual project, it looks like I made that error there, too. Copy-paste failure.

**Comment by jgwest** [comment]
No worries @namh0  :heart:
