### ISSUE TITLE
no matches for kind "ApplicationSet" in version "argoproj.io/v1alpha1"

### ISSUE THREAD

**Issue by nishit93-hub** [argoproj-labs/applicationset#413]
Hi, I am trying to use **kind** as ApplicationSet. However it is giving me an error 
`no matches for kind "ApplicationSet" in version "argoproj.io/v1alpha1"`

**Comment by JimFran** [comment]
@nishit93-hub Most probably you do not have the controller installed:

Install this CDR and later you can apply your ApplicationSet YML file:

```
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/applicationset/master/manifests/install.yaml
```

Regards,

**Comment by jgwest** [comment]
@nishit93-hub Install instructions are here: https://argocd-applicationset.readthedocs.io/en/stable/Getting-Started/

**Comment by nishit93-hub** [comment]
@JimFran @jgwest , yes the applicationSet controller was not installed. Thanks for the help!
