### ISSUE TITLE
applicationset stop generating apps if one of the app can not be created

### ISSUE THREAD

**Issue by waheedshahani** [argoproj-labs/applicationset#435]
I am using SCM Generator to dynamically create one app per github repo and target this repo to external cluster. As soon as a new repo is created app set generates an app for it because corresponding external cluster already exists via some magic. 

Lets say if I create 3 repos namely Repo1, Repo2 and Repo3. Assume that only Repo1 and Repo3 has corresponding external cluster and Repo2 has no cluster yet.   At this stage appset has discovered that it will create 3 apps, one for each repo. Fair enough. App set loops over 3 repos, creates app for Repo1, it wants to create app for Repo2 but it fails because there is no external cluster for Repo2. So far so good. At this stage app set does not loop over Repo 3 as it breaks due to Repo2 error. 

Below are some errors. 

`time="2021-12-11T21:32:58Z" level=info msg="generated 3 applications" generator="{<nil> <nil> <nil> <nil> 0xc000658900 <nil>}"
time="2021-12-11T21:32:58Z" level=error msg="error occurred during application generation: application spec is invalid: InvalidSpecError: cluster 'XXXXXXXXXXXXXXXXXXXXX' has not been configured"
time="2021-12-11T21:32:59Z" level=info msg="generated 3 applications" generator="{<nil> <nil> <nil> <nil> 0xc0004c2600 <nil>}"
time="2021-12-11T21:32:59Z" level=error msg="error occurred during application generation: application spec is invalid: InvalidSpecError: cluster 'XXXXXXXXXXXXXXXXXXXXX' has not been configured"`

Suspecting code here but I am not Go guy so can't read it correctly.
https://github.com/argoproj-labs/applicationset/blob/c574f5e0449e5a76d7c54918993474aebfe3c9e9/pkg/controllers/applicationset_controller.go#L113

**Comment by jgwest** [comment]
@waheedshahani which version of ApplicationSet controllere are you using?

**Comment by waheedshahani** [comment]
> @waheedshahani which version of ApplicationSet controllere are you using?

v0.2.0

**Comment by waheedshahani** [comment]
Looks like its fixed in new release v0.3.0 
https://github.com/argoproj-labs/applicationset/pull/372
Will close the issue
