### ISSUE TITLE
Application set v0.3.0 log regression

### ISSUE THREAD

**Issue by enys** [argoproj-labs/applicationset#445]
When running:
```
docker run --rm -it quay.io/argoproj/argocd-applicationset:v0.3.0 applicationset-controller
```
It errors out, producing 0 logs
Compared to 
```
docker run --rm -it quay.io/argoproj/argocd-applicationset:v0.2.0 applicationset-controller
```

This makes debugging CI failures, such as https://github.com/argoproj/argo-helm/pull/1070 tricky.

**Comment by mkilchhofer** [comment]
Also analysed When switching to json logformat, it seems to work again. Maybe due to PR https://github.com/argoproj-labs/applicationset/pull/373

```log
$ kubectl logs -f argocd-applicationset-74cb685876-29jbr
{"level":"info","ts":1641416299.9679651,"logger":"setup","msg":"ApplicationSet controller v0.3.0 using namespace 'default'","namespace":"default","COMMIT_ID":"fb33d2c26918be40e1d63d50eeab4f4ea2d16f01"}
{"level":"info","ts":1641416300.5976462,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","msg":"Starting configmap/secret informers","time":"2022-01-05T20:58:20Z"}
{"level":"info","msg":"Configmap/secret informer synced","time":"2022-01-05T20:58:20Z"}
{"level":"error","ts":1641416300.7069428,"logger":"setup","msg":"failed to create webhook handler","error":"Failed to get argocd settings: configmap \"argocd-cm\" not found","stacktrace":"main.main\n\t/workspace/main.go:158\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
```

Hmmm... `os.Exit(1)`. Really a hard fail, interesting...
https://github.com/argoproj-labs/applicationset/pull/341/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R210-R221

**Comment by enys** [comment]
Oh thanks, @mkilchhofer do you think it would make sense to switch to JSON format for the tests on the helm chart for now, making this a separate concern ?

**Comment by mkilchhofer** [comment]
Hmmm I don't feel confident to workaround regression introduced in 0.3.0 for the helm chart build/testing. We should fix it here in the upstream project and wait.
Up to v0.2.0 we could start the Appset pod without deploying ArgoCD.
