### ISSUE TITLE
Timeline for GA (or beta at least) ?

### ISSUE THREAD

**Issue by aelbarkani** [argoproj-labs/applicationset#72]
This component seems awesome. It solves clearly multi-cluster deployments challenges. Do you have a timeline to make it generally available (or at least beta) ?

**Comment by sbose78** [comment]
Hi @aelbarkani , we are working on coming up with a plan on this actively at the Dev community meetings. I will add a note once we lock in on a milestone.

**Comment by elocke** [comment]
Any updates? I'm itching to use this from some "release" point!

**Comment by OmerKahani** [comment]
Hi, we now have a milestone https://github.com/argoproj-labs/applicationset/milestone/1

**Comment by jgwest** [comment]
Think this can now be closed. :smile:
