### ISSUE TITLE
Synchronize go.(mod/sum) with latest Argo CD release

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#76]
The ApplicationSet `go.(mod/sum)` module metadata is currently targeting Argo CD v1.7.6. We should target v1.8.0 and sync the other shared dependency versions to be consistent with latest Argo CD `go.mod` versions, and then ensure it builds and the tests pass.

**Comment by kvendingoldo** [comment]
I'm working on that in https://github.com/argoproj-labs/applicationset/pull/89

**Comment by kvendingoldo** [comment]
@jgwest @dgoodwin @mgoodness @OmerKahani @wtam2018 @xianlubird please, review my change. I've tested it and it works fine

**Comment by jgwest** [comment]
Thanks @kvendingoldo, closing as done.
