### ISSUE TITLE
Implement additional Cluster generator E2E tests

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#80]
The proposed E2E test framework allows us to test ApplicationSet features against a live Kubernetes cluster and a live Argo CD instance. This issue tracks adding additional tests that specifically target the cluster generator.

PR #66 already includes a basic test of this generator, but this basic test was not an attempt at an exhaustive test of the functionality.

Should include, at least:
- Adding a new cluster (secret) should trigger ApplicationSet controller to create a new Application for it

**Comment by sbose78** [comment]
> Adding a new cluster (secret) should trigger ApplicationSet controller to create a new Application for it

+1
