### ISSUE TITLE
Add go test GitHub action to catch unit test regressions

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#83]
The Argo CD project uses GitHub actions that run `go test` (on non-E2E tests) for every PR commit. It would be great to include this here as well, to catch unit test regressions before they make it to `master`.

This should only run non-E2E tests, as E2E-tests are already covered in a separate GitHub Action in https://github.com/argoproj-labs/applicationset/pull/66

**Comment by jgwest** [comment]
I'm currently handling this on PR https://github.com/argoproj-labs/applicationset/pull/64.

**Comment by OmerKahani** [comment]
I think this can be closed #64 is merged

**Comment by jgwest** [comment]
@OmerKahani  :+1:
