### ISSUE TITLE
Add 'lint-go' and  'go mod tidy' to GitHub actions

### ISSUE THREAD

**Issue by jgwest** [argoproj-labs/applicationset#88]
Add `go lint`ing and `go mod tidy`ing to the ci-build GitHub action, based on what is already being done over in Argo CD https://github.com/argoproj/argo-cd/blob/master/.github/workflows/ci-build.yaml

As requested by @wtam2018 on https://github.com/argoproj-labs/applicationset/pull/64.

**Comment by kvendingoldo** [comment]
PR https://github.com/argoproj-labs/applicationset/pull/95

**Comment by jgwest** [comment]
Closing as done.
